include: package:very_good_analysis/analysis_options.5.0.0.yaml

analyzer:
  exclude:
    - build/**
    - '**/__generated__/**'
    - '**.g.*'
    - '**.gr.*'

linter:
  rules:
    public_member_api_docs: false
