targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator: # this for @RoutePage
        options:
          enable_cached_builds: true # Experimental
        generate_for:
          - lib/**/*_page.dart
      auto_route_generator:auto_router_generator: # this for @AutoRouterConfig
        options:
          enable_cached_builds: true # Experimental
        generate_for:
          - lib/router/router.dart 
